apiVersion: kamaji.clastix.io/v1alpha1
kind: TenantControlPlane
metadata:
  name: k8s-134
  labels:
    tenant.clastix.io: k8s-134
spec:
  controlPlane:
    deployment:
      replicas: 2
    service:
      serviceType: ClusterIP
  kubernetes:
    version: "v1.33.0"
    kubelet:
      cgroupfs: systemd
  networkProfile:
    port: 6443
  dataStore: default
  dataStoreSchema: default_k8s_134
  addons:
    coreDNS: {}
    kubeProxy: {}
    konnectivity:
      server:
        port: 8132
      agent:
        mode: DaemonSet
